package app;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.ResponseBody;

public class AddHomeController {
    @Autowired
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private HomeRepository homeRepository;

    public @ResponseBody
    Iterable<Home> getAllHomes() {
        return homeRepository.findAll();
    }

}