package app;

import org.springframework.http.HttpEntity;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@RestController
public class ConnectionController {

  private static final String FORM_VIEW = "/connection";
  private static final String WELCOME_VIEW = "/home";//"newuser.page";
  private static final String PATH = "/connection";

  @Autowired // This means to get the bean called userRepository
           // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @RequestMapping(value = PATH, method = RequestMethod.GET)
  public String connect() {
    System.out.println("connection as 'get' is invalid !");
    return "connection form invalid";
  }

  @ModelAttribute("User")
  public User populateUser() {
    User user = new User();
    return user;
  }

  @RequestMapping(value = PATH, method = RequestMethod.POST)
  public String connect(@ModelAttribute("User") User user,
  BindingResult result, Model model) {

    System.out.println(user.getName());
    System.out.println(user.getEmail());
    // System.out.println(user.getPassword());
    userRepository.save(user);
    return WELCOME_VIEW;
  }

  @GetMapping(path="/getAllUsers")
  public @ResponseBody Iterable<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }

}
